// <auto-generated />
using System;
using HeaderManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StoreProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241216144159_AB")]
    partial class AB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StoreProject.Models.DetailModel", b =>
                {
                    b.Property<string>("Column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeaderRowFunding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<Guid>("RowPointer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Details");
                });

            modelBuilder.Entity("StoreProject.Models.HeaderModel", b =>
                {
                    b.Property<string>("Column1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Column9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<Guid>("RowPointer")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.ToTable("Headers");
                });
#pragma warning restore 612, 618
        }
    }
}
